<a href="https://colab.research.google.com/github/axelmartinezportillo/elt-data-pipelin2523182022/blob/main/notebooks/ETL_Cursos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
url = "https://raw.githubusercontent.com/axelmartinezportillo/elt-data-pipelin2523182022/refs/heads/main/data/raw/A_cursos.csv"
df = pd.read_csv(url)
df.head()

  id_curso          curso         docente creditos
0     C200     Matemática  Lic. Hernández        3
1     C201   Programación     Mtra. Pérez        4
2     C202  Base de Datos    Mtra. Rivera        4
3     C203      Redacción      Ing. López        4
4     C204         Inglés     Ing. Romero        5

In [3]:
#exploracion de datos
df.shape
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id_curso  13 non-null     object
 1   curso     13 non-null     object
 2   docente   13 non-null     object
 3   creditos  13 non-null     object
dtypes: object(4)
memory usage: 548.0+ bytes

id_curso    0
curso       0
docente     0
creditos    0
dtype: int64

In [4]:
#Limpieza
cursos = df.copy()
cursos.columns = cursos.columns.str.strip().str.lower()

for col in cursos.select_dtypes(include='object').columns:
    cursos[col] = cursos[col].astype(str).str.strip()

# Limpiar columna créditos
cursos['creditos'] = cursos['creditos'].str.replace(' cr', '', case=False)
cursos['creditos'] = pd.to_numeric(cursos['creditos'], errors='coerce')

cursos = cursos.replace(['nan', 'None', ''], pd.NA)
cursos = cursos.replace(r'^\s*$', pd.NA, regex=True)
cursos = cursos.drop_duplicates()
print("Paso 9: Limpieza de cursos completada.")

Paso 9: Limpieza de cursos completada.

In [5]:
#seapara datos validos y rechazados
validos = cursos[cursos['id_curso'].notna() &
          cursos['curso'].notna()].copy()
rechazados = cursos[cursos['id_curso'].isna() |
              cursos['curso'].isna()].copy()
print(f"Paso 10: Separación de cursos finalizada. Válidos: {len(validos)}, Rechazados: {len(rechazados)}")

Paso 10: Separación de cursos finalizada. Válidos: 12, Rechazados: 0

In [7]:
#motivo de rechazo
def motivo_cur(row):
    motivos = []
    if pd.isna(row['id_curso']): motivos.append("id_curso_vacio")
    if pd.isna(row['curso']): motivos.append("nombre_curso_vacio")
    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo_cur, axis=1)

In [8]:
#exportar archivos
validos.to_csv("cursos_curated.csv", index=False)
rechazados.to_csv("cursos_rejects.csv", index=False)
print(" Archivos de cursos exportados.")

 Archivos de cursos exportados.

In [9]:
#CONECTAR RENDER
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_user:6r5AQWoE44HrllVAUznGZiLVeK6jjHfX@dpg-d6qu5ochg0os73b4g0v0-a.oregon-postgres.render.com/etl_seguros_fv1v"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 38.5 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11
   ?column?
0         1

In [10]:
#cargar datos en postegre
validos.to_sql('cursos_curated',
      engine,
      if_exists='append',
               index=False)
rechazados.to_sql('cursos_rejects',
            engine,
              if_exists='append',
                  index=False)
print("Paso 14: Carga de cursos a Render completada.")

Paso 14: Carga de cursos a Render completada.

In [11]:
#validar carga
pd.read_sql(
    "SELECT * FROM cursos_curated",
    engine)

   id_curso          curso         docente  creditos
0      C200     Matemática  Lic. Hernández         3
1      C201   Programación     Mtra. Pérez         4
2      C202  Base de Datos    Mtra. Rivera         4
3      C203      Redacción      Ing. López         4
4      C204         Inglés     Ing. Romero         5
5      C205         Física     Mtra. Pérez         4
6      C206        Química    Lic. Morales         3
7      C207       Historia    Mtra. Rivera         4
8      C208    Estadística     Lic. Castro         3
9      C209          Ética    Mtra. Rivera         3
10     C210     Diseño Web     Mtra. Pérez         3
11     C211     Algoritmos     Ing. Romero         5